#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.

TOTAL_STAGES=5

ENV_FILE="${ENV_FILE:-.wizard-values}"

banner "墨笺 · 外部服务开通（giscus 留言墙 + Formspree 投书）"

# ── Stage 1: 仓库开 Discussions ───────────────────────────────────────────
stage "GitHub — 开启 Discussions"
say "giscus 以仓库 Discussions 存储留言，需仓库为 public 且开启 Discussions。"
open_url "https://github.com/L-xuanxiao/mojian/settings"
step "确认仓库是 Public（私有仓库 giscus 无法使用）。"
step "Settings → General → Features 区，勾选「Discussions」。"
pause "已开启 Discussions？回车继续"

# ── Stage 2: 安装 giscus app ──────────────────────────────────────────────
stage "GitHub — 安装 giscus 应用"
say "giscus 应用获得读写 Discussions 的授权，只授权 mojian 一个仓库即可。"
open_url "https://github.com/apps/giscus"
step "点「Install」→ 选你的账号 → 「Only select repositories」→ 选 mojian → Install。"
pause "已安装并授权 mojian？回车继续"

# ── Stage 3: giscus.app 生成配置 ──────────────────────────────────────────
stage "giscus — 生成配置并抄回四个值"
say "giscus.app 的配置器会输出一段 script，其中有我们需要的四个值。"
open_url "https://giscus.app/zh-CN"
step "「repository」填：L-xuanxiao/mojian（校验通过会出现绿色成功提示）。"
step "「页面 ↔ discussion 映射关系」选：pathname。"
step "「Discussion 分类」选一个分类（建议 General），记下属性的值。"
note "在页面底部生成的 <script> 里找：data-repo / data-repo-id / data-category / data-category-id"
ask GISCUS_REPO "data-repo（形如 L-xuanxiao/mojian）:"
ask GISCUS_REPO_ID "data-repo-id（形如 R_kgDOxxxx）:"
ask GISCUS_CATEGORY "data-category（形如 General）:"
ask GISCUS_CATEGORY_ID "data-category-id（形如 DIC_kwDOxxxx）:"
write_env GISCUS_REPO "$GISCUS_REPO"
write_env GISCUS_REPO_ID "$GISCUS_REPO_ID"
write_env GISCUS_CATEGORY "$GISCUS_CATEGORY"
write_env GISCUS_CATEGORY_ID "$GISCUS_CATEGORY_ID"

# ── Stage 4: Formspree 建表单 ─────────────────────────────────────────────
stage "Formspree — 创建投书表单"
say "「此间 · 往来」的投书表单走 Formspree，免费额度对个人站足够。"
open_url "https://formspree.io/forms"
step "登录/注册 Formspree（可用 GitHub 账号登录）。"
step "「+ New form」→ 命名随意（如 mojian-contact）→ 创建。"
step "表单的 Integration/Endpoint 处复制完整地址，形如 https://formspree.io/f/xxxxxx。"
ask FORMSPREE_ENDPOINT "粘贴 endpoint（https://formspree.io/f/...）:"
write_env FORMSPREE_ENDPOINT "$FORMSPREE_ENDPOINT"

# ── Stage 5: 汇总交回 ─────────────────────────────────────────────────────
stage "汇总 — 把五个值交给 AI"
say "全部收齐。把下面这段原样发回给 AI，它会填入 src/site.config.ts："
printf '\n'
printf '  giscus.repo       = %s\n' "$GISCUS_REPO"
printf '  giscus.repoId     = %s\n' "$GISCUS_REPO_ID"
printf '  giscus.category   = %s\n' "$GISCUS_CATEGORY"
printf '  giscus.categoryId = %s\n' "$GISCUS_CATEGORY_ID"
printf '  formspree.endpoint = %s\n' "$FORMSPREE_ENDPOINT"
printf '\n'
note "这些值都会出现在公开前端代码里，不属于密钥；本向导存的 .wizard-values 用完可删。"
pause "回车结束"

finish
